#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:

  sql.init.mode: always

  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: create-drop
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
        id.new_generator_mappings: false
  datasource:
#database.url=jdbc:h2:/Users/taras/Downloads/Vacancy/h2db/h2
    driver-class-name: org.h2.Driver

    # ImMemory
    url: jdbc:h2:mem:resume23;DB_CLOSE_ON_EXIT=FALSE
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:resume23
    # Absolute path
#        url: jdbc:h2:/Users/taras/Downloads/resume_boot23/h2db/h2
    #    tcp: jdbc:h2:tcp://localhost:9092/Users/taras/Downloads/resume_boot23/h2db/h2
    # Relative path form current dir
    #    url: jdbc:h2:./resume23
    # Relative path from home
    #    url: jdbc:h2:~/resume23
    #    tcp: jdbc:h2:tcp://localhost:9092/~/resume23
    username: sa
    password:
#  h2.console.enabled: true

  # Jackson Serialization Issue Resolver
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
    cache-names: users
    caffeine.spec: maximumSize=5000,expireAfterAccess=60s

logging:
  level:
    root: WARN
    ua.top.bootjava: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

springdoc.swagger-ui.path: /swagger



