DROP TABLE IF EXISTS RATE;
DROP TABLE IF EXISTS VOTE;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS RESUME;
DROP TABLE IF EXISTS FRESHEN_GOAL;
DROP TABLE IF EXISTS FRESHEN;
DROP TABLE IF EXISTS USERS CASCADE;
DROP SEQUENCE IF EXISTS GLOBAL_SEQ;

CREATE SEQUENCE "GLOBAL_SEQ" START WITH 100000 INCREMENT BY 1 MINVALUE 100000 MAXVALUE 999999999 NOCACHE NOCYCLE;
CREATE TABLE IF NOT EXISTS USERS
(
    ID INTEGER DEFAULT NEXTVAL('GLOBAL_SEQ') PRIMARY KEY NOT NULL,
    NAME                  VARCHAR(255)             NOT NULL,
    EMAIL                 VARCHAR(255)             NOT NULL,
    PASSWORD              VARCHAR(255)             NOT NULL,
    REGISTERED            TIMESTAMP DEFAULT NOW(),
    ENABLED               BOOLEAN   DEFAULT TRUE
);
CREATE UNIQUE INDEX IF NOT EXISTS USERS_UNIQUE_EMAIL_IDX ON USERS (EMAIL);

CREATE TABLE IF NOT EXISTS USER_ROLES
(
    USER_ID                INTEGER NOT NULL,
    ROLE                   VARCHAR(255),
    CONSTRAINT USER_ROLES_IDX UNIQUE (USER_ID, ROLE),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FRESHEN
(
    ID INTEGER DEFAULT NEXTVAL('GLOBAL_SEQ') PRIMARY KEY NOT NULL,
    RECORDED_DATE TIMESTAMP           DEFAULT now() NOT NULL,
    LANGUAGE      VARCHAR(255)                      NOT NULL,
    LEVEL         VARCHAR(255)                      NOT NULL,
    WORKPLACE     VARCHAR(255)                      NOT NULL,
    USER_ID       INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FRESHEN_GOAL
(
    FRESHEN_ID INTEGER NOT NULL,
    GOAL       VARCHAR(255),
    FOREIGN KEY (FRESHEN_ID) REFERENCES FRESHEN (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESUME
(
    ID INTEGER DEFAULT NEXTVAL('GLOBAL_SEQ') PRIMARY KEY NOT NULL,
    TITLE        VARCHAR(255)   NOT NULL,
    NAME         VARCHAR(255)   NOT NULL,
    AGE          VARCHAR(255)   NOT NULL,
    ADDRESS      VARCHAR(255)   NOT NULL,
    SALARY       INTEGER        NOT NULL,
    WORK_BEFORE  VARCHAR(255)   NOT NULL,
    URL          VARCHAR(255)   NOT NULL,
    SKILLS       VARCHAR(255)   NOT NULL,
    RELEASE_DATE TIMESTAMP      NOT NULL,
    FRESHEN_ID   INTEGER        NOT NULL,
    CONSTRAINT RESUME_IDX UNIQUE (TITLE, WORK_BEFORE),
    FOREIGN KEY (FRESHEN_ID) REFERENCES FRESHEN (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VOTE
(
    ID INTEGER DEFAULT NEXTVAL('GLOBAL_SEQ') PRIMARY KEY NOT NULL,
    LOCAL_DATE DATE      NOT NULL,
    RESUME_ID  INTEGER   NOT NULL,
    USER_ID    INTEGER   NOT NULL,
    CONSTRAINT VOTE_IDX UNIQUE (RESUME_ID, USER_ID),
    FOREIGN KEY (RESUME_ID) REFERENCES RESUME (ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RATE
(
    ID INTEGER DEFAULT NEXTVAL('GLOBAL_SEQ') PRIMARY KEY NOT NULL,
    NAME               VARCHAR(255)          NOT NULL,
    VALUE_RATE         DOUBLE                NOT NULL,
    LOCAL_DATE         DATE                  NOT NULL,
    CONSTRAINT RATE_IDX UNIQUE (NAME)
);
